### ISSUE TITLE
Training errors in dataloader

### ISSUE THREAD

**Issue by hguq** [HuangOwen/VVTQ#1]
In training, such error is reported, but the training was not killed. What does this error mean?

```
Initialization:  [  0/782]  eta: 1:45:01    time: 8.0584  data: 6.7870  max mem: 311
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f760335bca0>
Traceback (most recent call last):
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/multiprocessing/connection.py", line 930, in wait
    ready = selector.select(timeout)
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/gqy/.conda/envs/vvtq/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 163935) is killed by signal: Aborted.
```

**Comment by HuangOwen** [comment]
Thanks for your interest in our work. This is because we use multi-processing distributed training by default. It's normal that there are some error appears in one thread. You can choose not to use multi-processing distributed training. You could also refer to this discussion: https://github.com/pytorch/pytorch/issues/8976

**Comment by hguq** [comment]
Thank you, although the error appears, the training can finish.

**Comment by thanhkm** [comment]
@hguq how did you solve the problem ?
